#! /usr/bin/python3

from langs._utils import args, load

import sys

# This module acts as requests router.
# It should be called by `execlp' with the following arguments
# mode lang_name src_file_path exec_file_path temp_dir_path

if len(sys.argv) != 6:
    # In total, there are five elements in `sys.argv'
    sys.exit(0)


mode, lang, src_file_path, exec_file_path, temp_dir_path = args(5)

processor = load(lang)

if mode == 'proc':
    with open('/home/wo/woj/log/exec.log', 'a') as f:
        f.write('pygent: proc, lang = %s' % lang)
        f.write('\n')

    processor.do(src_file_path,
                 exec_file_path,
                 temp_dir_path)
elif mode == 'exec':
    with open('/home/wo/woj/log/exec.log', 'a') as f:
        f.write('pygent: exec, lang = %s' % lang)
        f.write('\n')

    processor.exec_(src_file_path,
                    exec_file_path,
                    temp_dir_path)

