# This is restricted function table for lua generated by syscall_recorder.
# It is intended only as a recommended RF table for your security settings.
# Generated on ubuntu 3.13.0-48-generic x86_64; 2015-03-27T22:47:29.463064

from ._fundamental import RFTable

rf = RFTable()

rf.access = -1
rf.arch_prctl = 1
rf.brk = 3
rf.close = -1
rf.execve = 1
rf.exit_group = 1
rf.fstat = -1
rf.mmap = -1
rf.mprotect = -1
rf.munmap = 2
rf.open = -1
rf.read = -1
rf.rt_sigaction = 2
rf.write = 5
